---
- name: Harden Amazon Linux fleet
  hosts: amazon_linux_targets
  gather_facts: true
  become: true

  vars:
    os_hardening_enabled: true
    ssh_hardening_enabled: true
    sysctl_hardening_enabled: true
    os_hidepid_enabled: false
    os_security_packages_clean: false
    os_minimize_access_enabled: false
    os_auditd_enabled: false
    harden_sysctl_settings:
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.default.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv4.conf.default.accept_source_route: 0
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.default.accept_redirects: 0
      net.ipv4.conf.all.log_martians: 1
      net.ipv4.conf.default.log_martians: 1
      kernel.randomize_va_space: 2
      net.ipv4.ip_forward: 1

  collections:
    - devsec.hardening

  pre_tasks:
    - name: Ensure system up-to-date (RedHat/Amazon)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family in ["RedHat","Amazon"]

    - name: Ensure system up-to-date (Debian/Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
